//
// ROOT macro: beamburn.C (autogenerated by xyscan)
// xyscan Version 3.3.3
// Date: Mon Oct 10 18:48:56 2016
// Scanned by: jason
// Source: /Users/jason/Dropbox/Screenshots/Screen Shot 2016-10-10 at 6.46.11 PM.gif
// Comment: 
//
#include "TROOT.h"
#include "TH1D.h"
#include "TCanvas.h"
#include "TStyle.h"
#include "TGraphAsymmErrors.h"

void beamburn()
{

    TF1 *fexp = new TF1("fexp","TMath::Exp([0]-x/[2])",0,6);
    fexp->SetParameters(1.69,5.0);
    fexp->SetLineStyle(2);

    gROOT->SetStyle("Plain");
    gStyle->SetOptFit(0);
    gStyle->SetOptStat(0);

    TCanvas *c1 = new TCanvas("c1","c1",720,720);
    c1->SetTickx(1);
    c1->SetTicky(1);
    c1->SetBorderSize(1);
    c1->SetFillColor(0);

    TH1D *histo = new TH1D("histo","Part 2 ATLAS/CMS @ 0.4m", 100, -0.5, 5.25);
    histo->SetMinimum(0);
    histo->SetMaximum(6.0);
    histo->SetStats(false);
    histo->GetXaxis()->SetTitle("time [hours]");
    histo->GetYaxis()->SetTitle("Luminosity [10^{29} cm^{-2}s^{-1}]");
    gPad->SetLogy(0);
    gPad->SetLogx(0);
    histo->Draw();

    double x[31];
    double y[31];
    double dxlow[31];
    double dxup[31];
    double dylow[31];
    double dyup[31];
    int n = 0;
    x[n] = 0.096831;	y[n] = 5.40249;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 0.164319;	y[n] = 5.32313;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 0.214202;	y[n] = 5.24943;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 0.28169;	y[n] = 5.15306;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 0.375587;	y[n] = 5.04535;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 0.495892;	y[n] = 4.9093;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 0.616197;	y[n] = 4.77324;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 0.754108;	y[n] = 4.62018;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 0.871479;	y[n] = 4.51814;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 1.027;	y[n] = 4.37642;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 1.14437;	y[n] = 4.26304;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 1.26467;	y[n] = 4.17234;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 1.37324;	y[n] = 4.06463;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 1.53462;	y[n] = 3.93424;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 1.6608;	y[n] = 3.8322;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 1.78697;	y[n] = 3.73583;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 1.91315;	y[n] = 3.64512;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 2.05399;	y[n] = 3.54875;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 2.21538;	y[n] = 3.44104;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 2.37089;	y[n] = 3.33333;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 2.56749;	y[n] = 3.21429;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 2.69953;	y[n] = 3.13492;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 2.84624;	y[n] = 3.06122;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 3.04284;	y[n] = 2.93084;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 3.31573;	y[n] = 2.79478;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 3.5534;	y[n] = 2.65873;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 3.81455;	y[n] = 2.55102;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 3.99354;	y[n] = 2.45465;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 4.25176;	y[n] = 2.34694;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 4.55692;	y[n] = 2.22222;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;
    x[n] = 4.78286;	y[n] = 2.13719;	dxlow[n] = 0;	dxup[n] = 0;	dylow[n] = 0;	dyup[n] = 0;	n++;

    TGraphAsymmErrors *xyscan = new TGraphAsymmErrors(n, x, y, dxlow, dxup, dylow, dyup);
    xyscan->SetMarkerStyle(20);
    xyscan->SetMarkerColor(1);
    xyscan->Draw("PE same");
    fexp->Draw("same");

}
