//
// ROOT macro: beamburn.C (autogenerated by xyscan)
// xyscan Version 3.3.3
// Date: Mon Oct 10 18:48:56 2016
// Scanned by: jason
// Source: /Users/jason/Dropbox/Screenshots/Screen Shot 2016-10-10 at 6.46.11 PM.gif
// Comment: 
//
#include "TROOT.h"
#include "TH1D.h"
#include "TCanvas.h"
#include "TStyle.h"
#include "TGraphAsymmErrors.h"

TH2D *h_T_ell;
TH1D *h_ell;
TH1D *h_ell_max;
TGraphAsymmErrors *g_ell_max;

void OptimizeUptime()
{

  char saythis[500];

    TF1 *fexp = new TF1("fexp","TMath::Exp([0]-x/[2])",0,6);
    fexp->SetLineStyle(2);

    double ell = 5.0;//hours, length of fill
    double T   = 5.0;//hours, length between fills
    double tau = 10.0;//hours
    double metric = 0.0;
    fexp->SetParameters(1.69,tau);

    double MarginOfError = 0.02;

    int nBins    = 100;
    double binup = 20;

    h_T_ell = new TH2D("h_T_ell","h_T_ell", nBins,0,binup, nBins,0,binup);
    h_ell_max = new TH1D("h_ell_max","h_ell_max; L (length of fill) [hours]", nBins,0,binup);
    g_ell_max = new TGraphAsymmErrors(nBins);

    TCanvas *c1 = new TCanvas("c1","c1");
    
    for(int i=1; i<nBins+1; i++){
      for(int j=1; j<nBins+1; j++){

        T   = h_T_ell->GetXaxis()->GetBinCenter(i);
        ell = h_T_ell->GetYaxis()->GetBinCenter(j);

        metric = fexp->Integral(0,ell)/(ell+T);
        h_T_ell->SetBinContent(i,j, metric);

        //cout << ell << "  " << T << "  " << metric << endl;

      }
    }

    for(int i=1; i<nBins+1; i++){


      h_ell = (TH1D*)h_T_ell->ProjectionY("h_ell",i,i);
      double maxval = h_ell->GetMaximum();
      int maxbin = 0;
      int maxbin_lo = 0;
      int maxbin_hi = 0;
      for(int j=1; j<nBins+1; j++){
        double bincont = h_ell->GetBinContent(j);
        if(bincont==maxval){
          maxbin = j;
          break;
        }
      }
      for(int j=maxbin; j>0; j--){
        double bincont = h_ell->GetBinContent(j);
        if(bincont<(1.0-MarginOfError)*maxval){
          maxbin_lo = j;
          break;
        }
      }
      for(int j=maxbin; j<nBins+1; j++){
        double bincont = h_ell->GetBinContent(j);
        if(bincont<(1.0-MarginOfError)*maxval){
          maxbin_hi = j;
          break;
        }
      }
      h_ell_max->SetBinContent(i,h_ell->GetBinCenter(maxbin));
      //h_ell_max->SetBinError  (i,h_ell->GetBinCenter(maxbin_hi)-h_ell->GetBinCenter(maxbin));
      h_ell_max->SetBinError  (i,0);

      g_ell_max->SetPoint(i-1,h_ell_max->GetBinCenter(i),h_ell_max->GetBinContent(i));
      g_ell_max->SetPointError(i-1,0,0,h_ell->GetBinCenter(maxbin)-h_ell->GetBinCenter(maxbin_lo),
                                       h_ell->GetBinCenter(maxbin_hi)-h_ell->GetBinCenter(maxbin));



      //cout << maxbin << "  " << maxbin_lo << "  " << maxbin_hi << "    " << maxval << endl;
      if(i==15){
        h_ell->Draw();
        cout << "                 " << 
          h_ell_max->GetBinCenter(i) << "  " << 
          h_ell_max->GetBinContent(i) << "  " << 
          h_ell->GetBinCenter(maxbin)-h_ell->GetBinCenter(maxbin_lo) << "  " << 
          h_ell->GetBinCenter(maxbin_hi)-h_ell->GetBinCenter(maxbin) << endl;
        //break;
      }

    }


    gStyle->SetOptStat(0);
    TCanvas *c2 = new TCanvas("c2","c2");

    sprintf(saythis,"#tau = %2.1f hours",tau);
    h_T_ell->SetTitle(saythis);
    h_T_ell->GetXaxis()->SetTitle("T (downtime) [hours]");
    h_T_ell->GetYaxis()->SetTitle("L (length of fill) [hours]");
    h_T_ell->Draw("colz");
    h_ell_max->SetMarkerStyle(24);
    h_ell_max->SetMarkerColor(14);
    h_ell_max->SetLineColor  (14);
    g_ell_max->SetMarkerStyle(20);
    g_ell_max->SetMarkerColor(2);
    g_ell_max->SetLineColor  (2);
    g_ell_max->Draw("pe");
    h_ell_max->Draw("same,pe");

}
